version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command:  --wiredTigerCacheSizeGB 1.5
  davidka-app:
    image: top-api:latest
    container_name: davidka-app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/davidka-app/.env
    links:
      - mongodb
